LOCAL_PATH:= $(call my-dir)
HARDWARE_TI_OMAP4_BASE:= $(TOP)/hardware/ti/omap4xxx
OMAP4_DEBUG_MEMLEAK:= false

BUILD_HEAPTRACKED_SHARED_LIBRARY:=$(BUILD_SHARED_LIBRARY)
BUILD_HEAPTRACKED_EXECUTABLE:= $(BUILD_EXECUTABLE)

